routes:
  /subscribe/: members/subscribe
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account

collections:
  /:
    permalink: /{slug}/
    template: index
    published_at: asc


taxonomies:
  tag: /kata/{slug}/
  author: /sensei/{slug}/