routes:
  /subscribe/: members/subscribe
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /free/: free
  /store/: store

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /kata/{slug}/
  author: /sensei/{slug}/